In [45]:
import pickle
import sklearn
import modAL
from modAL.models import ActiveLearner
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from modAL.uncertainty import uncertainty_sampling
import sys

# 1. Read negative file #

In [2]:
neg_file= open("negative_xy.pickle", "rb")
negative_xy = pickle.load(neg_file)

In [3]:
negative_xy

array([[146,  14, 129, ...,  62, 255,   0],
       [154,  30, 171, ..., 158, 255,   0],
       [153,  25, 150, ..., 150, 255,   0],
       ..., 
       [153,  25, 146, ...,   0, 255,   0],
       [153,  25, 152, ...,   0, 255,   0],
       [155,  23, 168, ...,  90, 255,   0]])

In [4]:
np.random.shuffle(negative_xy)

In [11]:
negative_xy.shape

(300, 129)

# 2. Read positive file #

In [6]:
positive_xy = pickle.load(open( "positive_xy.pickle", "rb" ))

In [7]:
positive_xy

array([[153,  17, 128, ..., 136, 255,   1],
       [150,  19, 127, ...,  76, 255,   1],
       [155,  18, 126, ..., 156, 255,   1],
       ..., 
       [160,  20, 161, ..., 167, 255,   1],
       [154,  20, 139, ..., 255, 255,   1],
       [154,  21, 130, ..., 137, 255,   1]])

In [8]:
np.random.shuffle(positive_xy)

In [9]:
positive_xy

array([[155,  19, 158, ..., 182, 255,   1],
       [154,  14, 151, ..., 255, 255,   1],
       [152,  25, 127, ...,  45, 255,   1],
       ..., 
       [152,  21, 134, ..., 194, 255,   1],
       [152,  27, 134, ..., 235, 255,   1],
       [150,  20, 124, ...,  96, 255,   1]])

In [10]:
positive_xy.shape

(300, 129)

# 3. Get train and test examples #

## 3.1. Negative examples ##

In [12]:
negative_train = negative_xy[0:int(negative_xy.shape[0]/2),:]
negative_test = negative_xy[int(negative_xy.shape[0]/2):,:]

In [13]:
negative_train.shape

(150, 129)

In [14]:
negative_test.shape

(150, 129)

## 3.2. Positive examples ##

In [15]:
positive_train = positive_xy[0:int(positive_xy.shape[0]/2),:]
positive_test = positive_xy[int(positive_xy.shape[0]/2):,:]

In [16]:
positive_train.shape

(150, 129)

In [17]:
positive_test.shape

(150, 129)

## 3.3. Concatenate train examples together ##

In [18]:
train = np.concatenate((positive_train, negative_train))

In [19]:
train.shape

(300, 129)

## 3.4. Concatenate test examples together ##

In [20]:
test = np.concatenate((positive_test, negative_test))

In [21]:
test.shape

(300, 129)

## 3.5. Shuffle data ##

In [22]:
np.random.shuffle(train)

In [23]:
np.random.shuffle(test)

## 3.6. Separate x and y ##

### 3.6.1. Separate training data ###

In [24]:
x_train = train[:,:-1]

In [25]:
x_train.shape

(300, 128)

In [26]:
y_train = train[:,-1]

In [27]:
y_train.shape

(300,)

### 3.6.2. Separate test data ###

In [28]:
x_test = test[:,:-1]

In [29]:
x_test.shape

(300, 128)

In [30]:
y_test = test[:,-1]

In [31]:
y_test.shape

(300,)

# 4. Read X_pool file #

In [89]:
pool_file= open("X_pool.pickle", "rb")
X_pool = pickle.load(pool_file)

In [90]:
X_pool.shape

(998, 128)

In [91]:
ids_file= open("id_pool.pickle", "rb")
id_pool = pickle.load(ids_file)

In [92]:
sensor_id = []
time_stamp = []
frame = []
for i in range(len(id_pool)):
    sensor_timestamp = id_pool[i][0]
    if len(sensor_timestamp.decode("utf-8").split('_')) ==1:
        print(sensor_timestamp)
        sensor_id.append(sensor_timestamp.decode("utf-8").split('-')[0])
        time_stamp.append(sensor_timestamp.decode("utf-8").split('-')[1])
    else:     
        sensor_id.append(sensor_timestamp.decode("utf-8").split('_')[0])
        time_stamp.append(sensor_timestamp.decode("utf-8").split('_')[1])
    frame.append(id_pool[i][1])


In [93]:
type(frame[0])

int

# 5. Create classifier #

In [32]:
clf = RandomForestClassifier(n_estimators = 100)

In [33]:
clf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
pred = clf.predict(x_test)

In [35]:
sklearn.metrics.accuracy_score(y_test,pred)

0.97666666666666668

# 6. Create Active Learner #

In [71]:
learner = ActiveLearner(
    estimator=clf,
    query_strategy=uncertainty_sampling,
    X_training=x_train, y_training=y_train
)

In [86]:
n_queries = 3
n_instances = 2
accuracy = np.zeros(n_queries)
for idx in range(n_queries):
    y = []
    query_idx, query_instance = learner.query(X_pool, n_instances=n_instances)
    print (query_idx)
    for i in range(n_instances):
        y_new = input("Please input label for sensor: %s, timestamp: %s, frame: %d (1 if noise is present, 0 if noise is not present)" % (sensor_id[query_idx[i]],time_stamp[query_idx[i]],frame[query_idx[i]]))
        y.append(int(y_new))
    print('ARRAY: ',y)
    learner.teach(
        X=X_pool[query_idx],
        y=np.array(y).reshape(-1, )
    )
    X_pool = np.delete(X_pool, query_idx, axis=0)
    id_pool = np.delete(id_pool, query_idx, axis=0)
    print('Accuracy after query no. %d: %f' % (idx+1, learner.score(x_test, y_test)))
    accuracy[idx]=learner.score(x_test, y_test)
    
print(accuracy)

[302 321]
Please input label for sensor: b827eb2a1bce, timestamp: 1485820731.93, frame: 5 (1 if noise is present, 0 if noise is not present)1
Please input label for sensor: b827eb32f75c, timestamp: 1500188375.78, frame: 6 (1 if noise is present, 0 if noise is not present)0
ARRAY:  [1, 0]
Accuracy after query no. 1: 0.970000
[ 58 219]
Please input label for sensor: b827eb5895e9, timestamp: 1500156932.81, frame: 8 (1 if noise is present, 0 if noise is not present)0
Please input label for sensor: b827eb4e7821, timestamp: 1482670262.64, frame: 3 (1 if noise is present, 0 if noise is not present)0
ARRAY:  [0, 0]
Accuracy after query no. 2: 0.976667
[184 218]
Please input label for sensor: b827eb4e7821, timestamp: 1483759710.36, frame: 1 (1 if noise is present, 0 if noise is not present)1
Please input label for sensor: b827eb44506f, timestamp: 1488480548.66, frame: 8 (1 if noise is present, 0 if noise is not present)1
ARRAY:  [1, 1]
Accuracy after query no. 3: 0.973333
[ 0.97        0.976666

In [87]:
pool = X_pool

In [68]:
pool = np.delete(X_pool, query_idx, axis=0)

In [88]:
pool.shape

(986, 128)